<!-- Card Columns Example Social Feed-->
<div class="mb-0 mt-4">
    <i class="fa fa-newspaper-o"></i> News Feed</div>
<hr class="mt-2">
<div class="card-columns">
    <!-- Example Social Card-->
    <div class="card mb-3">
        <a href="#">
            <img class="card-img-top img-fluid w-100" src="https://unsplash.it/700/450?image=610" alt="">
        </a>
        <div class="card-body">
            <h6 class="card-title mb-1"><a href="#">David Miller</a></h6>
            <p class="card-text small">These waves are looking pretty good today!
                <a href="#">#surfsup</a>
            </p>
        </div>
        <hr class="my-0">
        <div class="card-body py-2 small">
            <a class="mr-3 d-inline-block" href="#">
                <i class="fa fa-fw fa-thumbs-up"></i>Like</a>
            <a class="mr-3 d-inline-block" href="#">
                <i class="fa fa-fw fa-comment"></i>Comment</a>
            <a class="d-inline-block" href="#">
                <i class="fa fa-fw fa-share"></i>Share</a>
        </div>
        <hr class="my-0">
        <div class="card-body small bg-faded">
            <div class="media">
                <img class="d-flex mr-3" src="http://placehold.it/45x45" alt="">
                <div class="media-body">
                    <h6 class="mt-0 mb-1"><a href="#">John Smith</a></h6>Very nice! I wish I was there! That looks amazing!
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item">
                            <a href="#">Like</a>
                        </li>
                        <li class="list-inline-item">·</li>
                        <li class="list-inline-item">
                            <a href="#">Reply</a>
                        </li>
                    </ul>
                    <div class="media mt-3">
                        <a class="d-flex pr-3" href="#">
                            <img src="http://placehold.it/45x45" alt="">
                        </a>
                        <div class="media-body">
                            <h6 class="mt-0 mb-1"><a href="#">David Miller</a></h6>Next time for sure!
                            <ul class="list-inline mb-0">
                                <li class="list-inline-item">
                                    <a href="#">Like</a>
                                </li>
                                <li class="list-inline-item">·</li>
                                <li class="list-inline-item">
                                    <a href="#">Reply</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer small text-muted">Posted 32 mins ago</div>
    </div>
    <!-- Example Social Card-->
    <div class="card mb-3">
        <a href="#">
            <img class="card-img-top img-fluid w-100" src="https://unsplash.it/700/450?image=180" alt="">
        </a>
        <div class="card-body">
            <h6 class="card-title mb-1"><a href="#">John Smith</a></h6>
            <p class="card-text small">Another day at the office...
                <a href="#">#workinghardorhardlyworking</a>
            </p>
        </div>
        <hr class="my-0">
        <div class="card-body py-2 small">
            <a class="mr-3 d-inline-block" href="#">
                <i class="fa fa-fw fa-thumbs-up"></i>Like</a>
            <a class="mr-3 d-inline-block" href="#">
                <i class="fa fa-fw fa-comment"></i>Comment</a>
            <a class="d-inline-block" href="#">
                <i class="fa fa-fw fa-share"></i>Share</a>
        </div>
        <hr class="my-0">
        <div class="card-body small bg-faded">
            <div class="media">
                <img class="d-flex mr-3" src="http://placehold.it/45x45" alt="">
                <div class="media-body">
                    <h6 class="mt-0 mb-1"><a href="#">Jessy Lucas</a></h6>Where did you get that camera?! I want one!
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item">
                            <a href="#">Like</a>
                        </li>
                        <li class="list-inline-item">·</li>
                        <li class="list-inline-item">
                            <a href="#">Reply</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="card-footer small text-muted">Posted 46 mins ago</div>
    </div>
    <!-- Example Social Card-->
    <div class="card mb-3">
        <a href="#">
            <img class="card-img-top img-fluid w-100" src="https://unsplash.it/700/450?image=281" alt="">
        </a>
        <div class="card-body">
            <h6 class="card-title mb-1"><a href="#">Jeffery Wellings</a></h6>
            <p class="card-text small">Nice shot from the skate park!
                <a href="#">#kickflip</a>
                <a href="#">#holdmybeer</a>
                <a href="#">#igotthis</a>
            </p>
        </div>
        <hr class="my-0">
        <div class="card-body py-2 small">
            <a class="mr-3 d-inline-block" href="#">
                <i class="fa fa-fw fa-thumbs-up"></i>Like</a>
            <a class="mr-3 d-inline-block" href="#">
                <i class="fa fa-fw fa-comment"></i>Comment</a>
            <a class="d-inline-block" href="#">
                <i class="fa fa-fw fa-share"></i>Share</a>
        </div>
        <div class="card-footer small text-muted">Posted 1 hr ago</div>
    </div>
    <!-- Example Social Card-->
    <div class="card mb-3">
        <a href="#">
            <img class="card-img-top img-fluid w-100" src="https://unsplash.it/700/450?image=185" alt="">
        </a>
        <div class="card-body">
            <h6 class="card-title mb-1"><a href="#">David Miller</a></h6>
            <p class="card-text small">It's hot, and I might be lost...
                <a href="#">#desert</a>
                <a href="#">#water</a>
                <a href="#">#anyonehavesomewater</a>
                <a href="#">#noreally</a>
                <a href="#">#thirsty</a>
                <a href="#">#dehydration</a>
            </p>
        </div>
        <hr class="my-0">
        <div class="card-body py-2 small">
            <a class="mr-3 d-inline-block" href="#">
                <i class="fa fa-fw fa-thumbs-up"></i>Like</a>
            <a class="mr-3 d-inline-block" href="#">
                <i class="fa fa-fw fa-comment"></i>Comment</a>
            <a class="d-inline-block" href="#">
                <i class="fa fa-fw fa-share"></i>Share</a>
        </div>
        <hr class="my-0">
        <div class="card-body small bg-faded">
            <div class="media">
                <img class="d-flex mr-3" src="http://placehold.it/45x45" alt="">
                <div class="media-body">
                    <h6 class="mt-0 mb-1"><a href="#">John Smith</a></h6>The oasis is a mile that way, or is that just a mirage?
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item">
                            <a href="#">Like</a>
                        </li>
                        <li class="list-inline-item">·</li>
                        <li class="list-inline-item">
                            <a href="#">Reply</a>
                        </li>
                    </ul>
                    <div class="media mt-3">
                        <a class="d-flex pr-3" href="#">
                            <img src="http://placehold.it/45x45" alt="">
                        </a>
                        <div class="media-body">
                            <h6 class="mt-0 mb-1"><a href="#">David Miller</a></h6>
                            <img class="img-fluid w-100 mb-1" src="https://unsplash.it/700/450?image=789" alt="">I'm saved, I found a cactus. How do I open this thing?
                            <ul class="list-inline mb-0">
                                <li class="list-inline-item">
                                    <a href="#">Like</a>
                                </li>
                                <li class="list-inline-item">·</li>
                                <li class="list-inline-item">
                                    <a href="#">Reply</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer small text-muted">Posted yesterday</div>
    </div>
</div>
<!-- /Card Columns-->
