<div class="container-fluid">
    <!-- Area Chart Example-->
    <?php echo $this->partial('partials/Charts/AreaChart.phtml'); ?>
    <div class="row">
        <div class="col-lg-8">
            <!-- Example Bar Chart Card-->
            <?php echo $this->partial('partials/Charts/BarChart.phtml'); ?>
        </div>
        <div class="col-lg-4">
            <!-- Example Pie Chart Card-->
            <?php echo $this->partial('partials/Charts/PieChart.phtml'); ?>
        </div>
    </div>
</div>
