<?php
/**
 * File generated by vendor/bin/apigility-upgrade-to-1.5.
 *
 * Original contents are available in config/test.config.php.dist.old
 */

return [
    'modules' => array_merge(include(__DIR__ . '/../config/modules.config.php'), [
        'ZendDeveloperTools',
        'ZF\\Apigility\\Admin',
    ]),
    'module_black_list' => [
        'API'
    ],
    'module_listener_options' => [
        'config_glob_paths' => [
            __DIR__ . '/autoload/{,*.}{global,local}-development.php',
        ],
        'config_cache_enabled' => false,
        'module_map_cache_enabled' => false,
    ],
];
