<?php
/** @var Zend\View\Renderer\PhpRenderer $this */
echo $this->doctype();
?>
<html lang="en">
    <?php echo $this->partial('partials/head.phtml'); ?>
    <body class="bg-dark">
        <?php echo $this->partial('partials/header.phtml'); ?>
        <div class="container">
            <div class="card card-login mx-auto mt-5">
                <div class="card-header">Login</div>
                <div class="card-body">
                    <form>
                        <div class="form-group">
                            <label for="username">User Name</label>
                            <input class="form-control" id="username" type="email" aria-describedby="emailHelp" placeholder="Enter User Name">
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input class="form-control" id="password" type="password" placeholder="Password">
                        </div>
                        <a id="login" class="btn btn-primary btn-block">Login</a>
                    </form>
                </div>
            </div>
        </div>
        <?php echo $this->partial('partials/footer.phtml'); ?>
    </body>
</html>
