<?php
/** @var Zend\View\Renderer\PhpRenderer $this */
echo $this->doctype();
?>
<html lang="en">
    <?php echo $this->partial('partials/login/Head.phtml', [ 'messages' => $this->messages ]); ?>
    <body class="bg-dark">
        <script src="<?php echo $this->basePath('js/login.js?v=' . rand(1, 100000)); ?>"></script>
        <?php echo $this->partial('partials/Header.phtml'); ?>
        <div class="container">
            <div class="card card-login mx-auto mt-5">
                <div class="card-header">Login</div>
                <div class="card-body">
                    <form id="login" data-parsley-validate>
                        <div class="form-group">
                            <label for="username">User Name</label>
                            <input class="form-control"
                                   id="username"
                                   type="text"
                                   placeholder="Enter User Name"
                                   required
                                   data-parsley-required-message="User Name is required"
                                   data-parsley-errors-container="#messages">
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input class="form-control"
                                   id="password"
                                   type="password"
                                   placeholder="Password"
                                   required
                                   data-parsley-required-message="Password is required"
                                   data-parsley-errors-container="#messages">
                        </div>
                        <a id="submit" class="btn btn-primary btn-block">Login</a>
                    </form>
                    <div id="messages" class="bs-callout bs-callout-danger hidden"></div>
                </div>
            </div>
        </div>
        <?php echo $this->partial('partials/modals/LoaderModal.phtml'); ?>
    </body>
</html>
