<?php
/** @var Zend\View\Renderer\PhpRenderer $this */
echo $this->doctype();
?>
<html lang="en">
    <?php echo $this->partial('partials/Head.phtml', [
        'menuRoute' => $this->menuRoute,
        'token'     => $this->token,
        'messages'  => $this->messages
    ]); ?>
    <body class="fixed-nav sticky-footer bg-dark" id="page-top">
        <!-- Navigation-->
        <?php echo $this->partial('partials/Navigation/NavigationBlock.phtml'); ?>
        <div class="content-wrapper">
            <div class="container-fluid">
                <!-- Breadcrumbs-->
                <?php echo $this->partial('partials/BreadCrumbs.phtml'); ?>
                <!-- Icon Cards-->
                <?php echo $this->partial('partials/IconCards.phtml'); ?>
                <!-- Area Chart Example-->
                <?php echo $this->partial('partials/Charts/AreaChart.phtml'); ?>
                <div class="row">
                    <div class="col-lg-8">
                        <!-- Example Bar Chart Card-->
                        <?php echo $this->partial('partials/Charts/BarChart.phtml'); ?>
                    </div>
                    <div class="col-lg-4">
                        <!-- Example Pie Chart Card-->
                        <?php echo $this->partial('partials/Charts/PieChart.phtml'); ?>
                    </div>
                </div>
                <!-- Example DataTables Card-->
                <?php echo $this->partial('partials/Datatable.phtml'); ?>
            </div>
            <?php echo $this->partial('partials/Footer.phtml'); ?>
        </div>
    </body>
</html>
