<link href="<?php echo $this->basePath('assets/SBAdmin/vendor/font-awesome/css/font-awesome.min.css'); ?>" rel="stylesheet" type="text/css">
<link href="<?php echo $this->basePath('assets/SBAdmin/css/sb-admin.css'); ?>" rel="stylesheet">
<link href="<?php echo $this->basePath('css/common.css?v=' . rand(1, 1000)); ?>" rel="stylesheet">
<link href="<?php echo $this->basePath('css/loading.css?v=' . rand(1, 1000)); ?>" rel="stylesheet">
