<script src="<?php echo $this->basePath('assets/SBAdmin/vendor/chart.js/Chart.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/SBAdmin/vendor/datatables/jquery.dataTables.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/SBAdmin/vendor/datatables/dataTables.bootstrap4.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/SBAdmin/js/sb-admin-datatables.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/SBAdmin/js/sb-admin-charts.min.js'); ?>"></script>
