<?php echo $this->partial('partials/JavaScript/ApplicationCoreJS.phtml', [
    'menuRoute' => $this->menuRoute,
    'token'     => $this->token,
    'messages'  => $this->messages
]);
?>
<script src="<?php echo $this->basePath('js/assets/jquery-ui.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('js/sessionHandler.js?v=' . rand(1, 1000)); ?>"></script>
<script src="<?php echo $this->basePath('js/dialogWidget.js?v=' . rand(1, 1000)); ?>"></script>
