<head>
    <?php echo $this->partial('partials/meta.phtml'); ?>
    <?php echo $this->partial('partials/CSS/BootstrapCoreCSS.phtml'); ?>
    <?php echo $this->partial('partials/CSS/ApplicationCoreCSS.phtml'); ?>
    <?php echo $this->partial('partials/JavaScript/BootstrapCoreJS.phtml'); ?>
    <?php echo $this->partial('partials/JavaScript/ApplicationCoreJS.phtml', [ 'messages'  => $this->messages ]); ?>
</head>
