<!-- Application Specific -->
<script src="<?php echo $this->basePath('js/assets/parsley.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('js/assets/jquery.easyModal.js'); ?>"></script>
<script src="<?php echo $this->basePath('js/assets/jquery.noty.packaged.min.js'); ?>"></script>
<?php echo $this->partial('partials/GlobalEmbedJS.phtml'); ?>
<script src="<?php echo $this->basePath('js/globalVars.js?v=' . rand(1, 1000)); ?>"></script>
<script src="<?php echo $this->basePath('js/globalLibrary.js?v=' . rand(1, 1000)); ?>"></script>
