<?php echo $this->partial('partials/modals/DefaultModal.phtml'); ?>
<?php echo $this->partial('partials/LoaderModal.phtml'); ?>
<?php echo $this->partial('partials/PageLevelJS.phtml'); ?>
<!--suppress ALL -->
<footer class="sticky-footer">
    <div class="container">
        <div class="text-center">
            <small>Copyright © Joshua M Pacheco <?php echo date('Y'); ?></small>
        </div>
    </div>
</footer>
<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fa fa-angle-up"></i>
</a>
