<head>
    <?php echo $this->partial('partials/meta.phtml'); ?>
    <?php echo $this->partial('partials/BootstrapCoreCSS.phtml'); ?>
    <?php echo $this->partial('partials/ApplicationCoreCSS.phtml'); ?>
    <?php echo $this->partial('partials/ViewLevelCSS.phtml'); ?>
    <?php echo $this->partial('partials/BootstrapCoreJS.phtml'); ?>
    <?php echo $this->partial('partials/ViewLevelJS.phtml', [
        'menuRoute' => $this->menuRoute,
        'token'     => $this->token,
        'messages'  => $this->messages
    ]);
?>
</head>
