<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Eye Chart Login">
    <meta name="author" content="Joshua M Pacheco">
    <?php echo $this->headTitle()->setAutoEscape(false)->setTranslatorEnabled(false); ?>
    <!-- Bootstrap core CSS-->
    <link href="<?php echo $this->basePath('assets/SBAdmin/vendor/bootstrap/css/bootstrap.css'); ?>" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="<?php echo $this->basePath('assets/SBAdmin/vendor/font-awesome/css/font-awesome.min.css'); ?>" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template-->
    <link href="<?php echo $this->basePath('assets/SBAdmin/css/sb-admin.css'); ?>" rel="stylesheet">

    <link href="<?php echo $this->basePath('css/common.css?v=' . rand(1, 1000)); ?>" rel="stylesheet">

    <script src="<?php echo $this->basePath('assets/SBAdmin/vendor/jquery/jquery.min.js'); ?>"></script>
    <script src="<?php echo $this->basePath('assets/SBAdmin/vendor/bootstrap/js/bootstrap.bundle.min.js'); ?>"></script>
    <!-- Core plugin JavaScript-->
    <script src="<?php echo $this->basePath('assets/SBAdmin/vendor/jquery-easing/jquery.easing.min.js'); ?>"></script>

    <script src="<?php echo $this->basePath('js/assets/parsley.min.js'); ?>"></script>
    <script src="<?php echo $this->basePath('js/assets/jquery.easyModal.js'); ?>"></script>
    <script src="<?php echo $this->basePath('js/assets/jquery.noty.packaged.min.js'); ?>"></script>

    <!-- Application Specific -->
    <?php echo $this->partial('partials/JSEmbed.phtml'); ?>
    <script src="<?php echo $this->basePath('js/globalVars.js?v=' . rand(1, 1000)); ?>"></script>
    <script src="<?php echo $this->basePath('js/globalLibrary.js?v=' . rand(1, 1000)); ?>"></script>
</head>
