<div id="defaultModalContainer" class="hidden">
    <div id="defaultModalBackground"></div>
    <div class="modal hidden" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="defaultModalLabel"></h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body"></div>
                <div class="modal-footer">
<!--                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>-->
<!--                    <a class="btn btn-primary" id="logout">Logout</a>-->
                </div>
            </div>
        </div>
    </div>
</div>
